#!/bin/bash

#cleanup
clear;

echo "***************************************";
echo "iBotPeaches .:. Auto Porting .:. ";
echo "***************************************";

#setup vars
dir=$PWD;

#helper vars
miui_path="$dir/raw_miui";
cm_path="$dir/raw_cm";
port_path="$dir/port";

#cleanup
if [ -d $dir/wip ]; then
    cd $dir/wip;
    rm -rf *;
else
   mkdir -p $dir/wip;
fi

#cleanup
if [ -d $dir/final_port ]; then
    cd $dir/final_port;
    rm -rf *;
else
   mkdir -p $dir/final_port;
fi

#Check for MIUI & CM
if [ ! -f $dir/raw_cm/boot.img ]; then
   echo "Missing CM Rom. Please drop CM rom (unzipped) into raw_cm";
   exit;
fi

if [ ! -d $dir/raw_miui/system ]; then
   echo "Missing MIUI Rom. Please drop MIUI rom (unzipped) into raw_miui";
   exit;
fi

#move CM base to port folder
if [ -d $dir/port ]; then
    rm -rf $dir/port;
fi

mkdir -p $dir/port

#begin copy
cd $dir/raw_cm;
cp -arf * ../port;

#delete CM specific stuff
rm -rf $dir/port/system/framework/*;
rm -rf $dir/port/system/app/*;
rm -rf $dir/port/system/font/*;
rm -rf $dir/port/system/media/*;
rm -rf $dir/port/system/xbin/su;

## BEGIN COPY OF MIUI FILES

#libs
cp -arf $miui_path/system/lib/content-types.properties $port_path/system/lib/content-types.properties;
cp -arf $miui_path/system/lib/liblbesec.so $port_path/system/lib/liblbesec.so;
cp -arf $miui_path/system/lib/liblocSDK_2.5OEM.so $port_path/system/lib/liblocSDK_2.5OEM.so;

#etc
cp -arf $miui_path/system/etc/yellowpage.db $port_path/system/etc/yellowpage.db;
cp -arf $miui_path/system/etc/telocation.td $port_path/system/etc/telocation.td;
cp -arf $miui_path/system/etc/spn-conf.xml $port_path/system/etc/spn-conf.xml;

#etc - permissions
cp -arf $miui_path/system/etc/permissions/com.nxp.mifare.xml $port_path/system/etc/permissions/com.nxp.mifare.xml;
cp -arf $miui_path/system/etc/permissions/miui-framework.xml $port_path/system/etc/permissions/miui-framework.xml;
cp -arf $miui_path/system/etc/permissions/com.google.android.media.effects.xml $port_path/system/etc/permissions/com.google.android.media.effects.xml;
cp -arf $miui_path/system/etc/permissions/com.google.widevine.software.drm.xml $port_path/system/etc/permissions/com.google.widevine.software.drm.xml;
cp -arf $miui_path/system/etc/permissions/com.google.android.maps.xml $port_path/system/etc/permissions/com.google.android.maps.xml;

#xbin
cp -arf $miui_path/system/xbin/su $port_path/system/xbin/su;
cp -arf $miui_path/system/xbin/invoke-as $port_path/system/xbin/invoke-as;

# the rest of MIUI
cp -arf $miui_path/system/app/* $port_path/system/app/;
cp -arf $miui_path/system/framework/* $port_path/system/framework/;
cp -arf $miui_path/system/fonts/* $port_path/system/fonts/;
cp -arf $miui_path/system/media/* $port_path/system/media/;

# Grab CM10 NFC && Gallery to fix Camera
cp -arf $cm_path/system/app/Nfc.apk $port_path/system/app/;
cp -arf $cm_path/system/app/Gallery2.apk $port_path/system/app/LegacyCMGallery.apk;

#kill off old MIUI Camera
rm -rf $port_path/system/app/LegacyCamera.apk;

## Use prebuilt updater.script & build.prop
## Saves about 200 lines of bash. (Those reserved for MIUI Build Scripts)
## Copy everything that is pre-made
cp -arf $dir/move_over/* $port_path/;

## BEGIN DECOMPILE
mkdir -p $dir/wip/jars/miui;
mkdir -p $dir/wip/jars/cm;
mkdir -p $dir/wip/apks;
mkdir -p $dir/wip/frames;

# IF the frameworks
for file in $port_path/system/framework/*.apk; do
  $dir/../tools/apktool if $file;
done

# decompile jars that need smali editing
$dir/../tools/apktool d --no-debug-info $port_path/system/framework/services.jar $dir/wip/jars/miui/services.jar.out
$dir/../tools/apktool d --no-debug-info $port_path/system/framework/framework.jar $dir/wip/jars/miui/framework.jar.out
$dir/../tools/apktool d --no-debug-info $port_path/system/framework/android.policy.jar $dir/wip/jars/miui/android.policy.jar.out
$dir/../tools/apktool d --no-debug-info $cm_path/system/framework/services.jar $dir/wip/jars/cm/services.jar.out
$dir/../tools/apktool d --no-debug-info $cm_path/system/framework/framework.jar $dir/wip/jars/cm/framework.jar.out
$dir/../tools/apktool d --no-debug-info $cm_path/system/framework/android.policy.jar $dir/wip/jars/cm/android.policy.jar.out

#decompile APKs that need editing.
$dir/../tools/apktool d --no-src $port_path/system/framework/framework-res.apk $dir/wip/frames/framework-res.apk
$dir/../tools/apktool d --no-src $port_path/system/app/Settings.apk $dir/wip/apks/Settings.apk
$dir/../tools/apktool d --no-src $port_path/system/app/LegacyCMGallery.apk $dir/wip/apks/LegacyCMGallery.apk

#lets merge smali that is just direct merge
# USING MIUI FOLDER AS LIVE

#kudos to Tejh for doing the long hours part
wip_cm=$dir/wip/jars/cm;
wip_miui=$dir/wip/jars/miui;

#auto merge framework
cp -arf $wip_cm/framework.jar.out/smali/android/view/GLES20*.smali $wip_miui/framework.jar.out/smali/android/view/;
cp -arf $wip_cm/framework.jar.out/smali/android/view/HardwareCanvas.smali $wip_miui/framework.jar.out/smali/android/view/;
cp -arf $wip_cm/framework.jar.out/smali/android/os/PowerManager*.smali $wip_miui/framework.jar.out/smali/android/os/;
cp -arf $wip_cm/framework.jar.out/smali/android/hardware/Camera*.smali $wip_miui/framework.jar.out/smali/android/hardware/;
cp -arf $wip_cm/framework.jar.out/smali/android/server/BluetoothA2dpService*.smali $wip_miui/framework.jar.out/smali/android/server/;
cp -arf $wip_cm/framework.jar.out/smali/android/webkit/WebView*.smali $wip_miui/framework.jar.out/smali/android/webkit/;
cp -arf $wip_cm/framework.jar.out/smali/com/android/internal/telephony/BaseCommands.smali $wip_miui/framework.jar.out/smali/com/android/internal/telephony/BaseCommands.smali
cp -arf $wip_cm/framework.jar.out/smali/com/android/internal/telephony/PhoneFactory.smali $wip_miui/framework.jar.out/smali/com/android/internal/telephony/PhoneFactory.smali
cp -arf $wip_cm/framework.jar.out/smali/com/android/internal/telephony/RIL*.smali $wip_miui/framework.jar.out/smali/com/android/internal/telephony/;
cp -arf $wip_cm/framework.jar.out/smali/com/android/internal/telephony/Samsung*.smali $wip_miui/framework.jar.out/smali/com/android/internal/telephony/;
cp -arf $wip_cm/framework.jar.out/smali/com/android/internal/telephony/QualcommSharedRIL*.smali $wip_miui/framework.jar.out/smali/com/android/internal/telephony/;


#todo

#manual diff
echo "Merge nativeSetStylusIconEnabled()";
sleep 1;
meld $wip_miui/services.jar.out/smali/com/android/server/input/InputManagerService.smali $wip_cm/services.jar.out/smali/com/android/server/input/InputManagerService.smali;

